# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.28.0.schema.json

PackageIdentifier: Microsoft.MSXML.4
PackageVersion: 4.0-SP3
DefaultLocale: en
ManifestType: version
ManifestVersion: 1.28.0