# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.12.0.schema.json

PackageIdentifier: Microsoft.UI.Xaml.2.2
PackageVersion: 2.21909.17002
DefaultLocale: en
ManifestType: version
ManifestVersion: 1.12.0