# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Purslane.RustDesk
PackageVersion: 1.4.6.29544831
ReleaseDate: 2026-03-05
InstallerLocale: en-US
InstallModes:
- interactive
- silent
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/rustdesk/rustdesk/releases/download/1.4.6/rustdesk-1.4.6-x86_64.msi
  InstallerSha256: 7AAD1F481B2FDF86166D082933071E7E9AAF7EFD3666A4204CDC5FD2F42B0E59
  InstallerType: msi
  ProductCode: '{552ED017-461C-4DE5-8739-E04466E938FB}'
- Architecture: x64
  InstallerType: exe
  InstallerUrl: https://github.com/rustdesk/rustdesk/releases/download/1.4.6/rustdesk-1.4.6-x86_64.exe
  InstallerSha256: 422ce31131e6537ea4f611ebf4a4d1804f28a6f58c83aa05065071c5958f1551
  InstallerSwitches:
    Silent: --silent-install
    SilentWithProgress: --silent-install
    Interactive: --install
  UpgradeBehavior: install
  Scope: machine
- Architecture: x86
  InstallerType: exe
  InstallerUrl: https://github.com/rustdesk/rustdesk/releases/download/1.4.6/rustdesk-1.4.6-x86-sciter.exe
  InstallerSha256: 1d009aef333dc9995bd4c1a58341fecfe4399352f5ce3fdfa6c545f1c155e93b
  InstallerSwitches:
    Silent: --silent-install
    SilentWithProgress: --silent-install
    Interactive: --install
  UpgradeBehavior: install
  Scope: machine
ManifestType: installer
ManifestVersion: 1.12.0
