# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: Microsoft.UI.Xaml.2.0
PackageVersion: 2.1810.18004
PackageLocale: en
Publisher: Microsoft Corporation
PackageName: Microsoft.UI.Xaml
PackageUrl: https://www.nuget.org/packages/Microsoft.UI.Xaml/2.0.181018004
License: MIT
ShortDescription: This package provides backward-compatible versions of Windows UI features including UWP XAML controls, dense control styles, and Fluent styles and materials. It is part of the Windows UI Library.
Moniker: uixaml20
Tags:
- microsoft-ui-xaml-2-0
- microsoftuixaml2.0
Documentations:
- DocumentLabel: Alternate Homepage
  DocumentUrl: https://github.com/microsoft/microsoft-ui-xaml
ManifestType: defaultLocale
ManifestVersion: 1.12.0