# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Microsoft.UI.Xaml.2.3
PackageVersion: 2.32002.13001
ReleaseDate: 2020-02-14
Platform:
- Windows.Universal
PackageFamilyName: Microsoft.UI.Xaml.2.3_8wekyb3d8bbwe
InstallerType: zip # A .nupkg archive with .appx files inside it.
NestedInstallerType: appx
Installers:
- Architecture: x64
  NestedInstallerFiles:
  - RelativeFilePath: tools\AppX\x64\Release\Microsoft.UI.Xaml.2.3.appx
  InstallerUrl: https://globalcdn.nuget.org/packages/microsoft.ui.xaml.2.3.200213001.nupkg
  InstallerSha256: 857c6b90c9e7b0b0466813ab3e00327e5c8d3fd2175b5f743b3a0d4580f0193a
  SignatureSha256: 697e72a8d7e2e24fbd2736b474d96bb4222149a7d5e49f14222a68598567ce09
- Architecture: x86
  NestedInstallerFiles:
  - RelativeFilePath: tools\AppX\x86\Release\Microsoft.UI.Xaml.2.3.appx
  InstallerUrl: https://globalcdn.nuget.org/packages/microsoft.ui.xaml.2.3.200213001.nupkg
  InstallerSha256: 857c6b90c9e7b0b0466813ab3e00327e5c8d3fd2175b5f743b3a0d4580f0193a
  SignatureSha256: d12f16f47608ab3f22977d9d927af62a865c7f6e34d925025eafaadd78a1633f
- Architecture: arm64
  NestedInstallerFiles:
  - RelativeFilePath: tools\AppX\arm64\Release\Microsoft.UI.Xaml.2.3.appx
  InstallerUrl: https://globalcdn.nuget.org/packages/microsoft.ui.xaml.2.3.200213001.nupkg
  InstallerSha256: 857c6b90c9e7b0b0466813ab3e00327e5c8d3fd2175b5f743b3a0d4580f0193a
  SignatureSha256: 9ef9ee69f920a4f5235b8d09e5ed5c62b8f718fe72610d0f8515ee3292c9972d
- Architecture: arm
  NestedInstallerFiles:
  - RelativeFilePath: tools\AppX\arm\Release\Microsoft.UI.Xaml.2.3.appx
  InstallerUrl: https://globalcdn.nuget.org/packages/microsoft.ui.xaml.2.3.200213001.nupkg
  InstallerSha256: 857c6b90c9e7b0b0466813ab3e00327e5c8d3fd2175b5f743b3a0d4580f0193a
  SignatureSha256: c8950d685f123bfe8643e3dc8359b8a980fbf3015f80834377972479235d2f2a
ManifestType: installer
ManifestVersion: 1.12.0