# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.12.0.schema.json

PackageIdentifier: Utopia.Eden.Zen4
PackageVersion: 0.2.1
DefaultLocale: en
ManifestType: version
ManifestVersion: 1.12.0