# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.28.0.schema.json

PackageIdentifier: Microsoft.DotNet.Native.Runtime.1.4
PackageVersion: 1.4.24201
DefaultLocale: en
ManifestType: version
ManifestVersion: 1.28.0