# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Microsoft.UI.Xaml.2.1
PackageVersion: 2.11906.6001
ReleaseDate: 2019-06-10
Platform:
- Windows.Universal
PackageFamilyName: Microsoft.UI.Xaml.2.1_8wekyb3d8bbwe
InstallerType: zip # A .nupkg archive with .appx files inside it.
NestedInstallerType: appx
Installers:
- Architecture: x64
  NestedInstallerFiles:
  - RelativeFilePath: tools\AppX\x64\Release\Microsoft.UI.Xaml.2.1.appx
  InstallerUrl: https://globalcdn.nuget.org/packages/microsoft.ui.xaml.2.1.190606001.nupkg
  InstallerSha256: a7bb45b97f1292f72cc2424e9fe73cb2ad84b51cf0843f7d33b9a3ca1e8c9da2
  SignatureSha256: 37a271ac18b6615fb051fe76fd485fea791ca1162b6e19b87a7e8ec55d40fc7f
- Architecture: x86
  NestedInstallerFiles:
  - RelativeFilePath: tools\AppX\x86\Release\Microsoft.UI.Xaml.2.1.appx
  InstallerUrl: https://globalcdn.nuget.org/packages/microsoft.ui.xaml.2.1.190606001.nupkg
  InstallerSha256: a7bb45b97f1292f72cc2424e9fe73cb2ad84b51cf0843f7d33b9a3ca1e8c9da2
  SignatureSha256: ab59912d3a77844860aaee6dcb2e9c9145804a0a16ec2dd6d73f92810865f303
- Architecture: arm64
  NestedInstallerFiles:
  - RelativeFilePath: tools\AppX\arm64\Release\Microsoft.UI.Xaml.2.1.appx
  InstallerUrl: https://globalcdn.nuget.org/packages/microsoft.ui.xaml.2.1.190606001.nupkg
  InstallerSha256: a7bb45b97f1292f72cc2424e9fe73cb2ad84b51cf0843f7d33b9a3ca1e8c9da2
  SignatureSha256: 5dbe821b26c58871a0ef090b773fc3e10226a509bb5abd91f9dba364d134387e
- Architecture: arm
  NestedInstallerFiles:
  - RelativeFilePath: tools\AppX\arm\Release\Microsoft.UI.Xaml.2.1.appx
  InstallerUrl: https://globalcdn.nuget.org/packages/microsoft.ui.xaml.2.1.190606001.nupkg
  InstallerSha256: a7bb45b97f1292f72cc2424e9fe73cb2ad84b51cf0843f7d33b9a3ca1e8c9da2
  SignatureSha256: ea410236e1a1506f1dc91c62611695f3d99d2e853a960a18bdff6a84925f5cd3
ManifestType: installer
ManifestVersion: 1.12.0