name: label

on:
  pull_request_target: # zizmor: ignore[dangerous-triggers]
    paths: ['manifests/**', 'fonts/**']

permissions: {}

jobs:
  label:
    permissions:
      pull-requests: write
    runs-on: ubuntu-slim
    steps:
      - uses: tj-actions/changed-files@9426d40962ed5378910ee2e21d5f8c6fcbf2dd96 # v47.0.6
        id: changed
        with:
          files: |
            manifests/**/*.installer.yaml
            fonts/**/*.installer.yaml

      - name: Label arm32
        shell: pwsh
        env:
          GH_TOKEN: ${{ github.token }}
          CHANGED: ${{ steps.changed.outputs.all_changed_files }}
          PR: ${{ github.event.pull_request.number }}
        run: |
          $archs = $env:CHANGED -split '\s+' | Where-Object { $_ } | ForEach-Object {
            yq '.Architecture, .Installers[].Architecture' $_
          } | Select-Object -Unique
          if ($archs -contains 'arm') {
            gh pr edit $env:PR --add-label 'Validation-arm32' --repo $env:GITHUB_REPOSITORY
          }
