name: label

on:
  pull_request_target:
    paths: ['manifests/**', 'fonts/**']

permissions:
  pull-requests: write

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      # This checkout might have unsafe content
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: tj-actions/changed-files@9426d40962ed5378910ee2e21d5f8c6fcbf2dd96 # v47.0.6
        id: changed
        with:
          files: |
            manifests/**/*.installer.yaml
            fonts/**/*.installer.yaml

      - name: Label arm32
        shell: pwsh
        env:
          GH_TOKEN: ${{ github.token }}
          CHANGED: ${{ steps.changed.outputs.all_changed_files }}
          PR: ${{ github.event.pull_request.number }}
        run: |
          Install-Module powershell-yaml -Force
          $archs = $env:CHANGED -split '\s+' | Where-Object { $_ } | ForEach-Object {
            (Get-Content $_ | ConvertFrom-Yaml).Installers.Architecture
          } | Select-Object -Unique
          if ($archs -contains 'arm') {
            gh pr edit $env:PR --add-label 'Validation-arm32' --repo $env:GITHUB_REPOSITORY
          }
